#!/usr/bin/env python3
"""Generate authentication tokens for testing the Hubble Agents API

This script generates both HMAC tokens (for development) and mock Clerk JWT tokens
(for testing JWT authentication flow).

Usage:
    python generate_token.py
    python generate_token.py --type hmac
    python generate_token.py --type jwt --org-id org-123 --user-id user-456
"""

import argparse
import base64
import hashlib
import hmac
import json
import os
import sys
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

# Try to import JWT library for Clerk token generation
try:
    import jwt

    HAS_JWT = True
except ImportError:
    HAS_JWT = False
    print("Warning: PyJWT not installed. JWT tokens will not be available.", file=sys.stderr)
    print("Install with: uv add pyjwt[crypto]", file=sys.stderr)


def generate_hmac_token(
    org_id: str = "default-org",
    user_id: str = "default-user",
    conversation_id: str = "00000000-0000-0000-0000-000000000001",
    secret: str | None = None,
) -> str:
    """Generate HMAC service token for development/testing

    Args:
        org_id: Organization ID
        user_id: User ID
        conversation_id: Conversation ID
        secret: HMAC secret (defaults to SERVICE_AUTH_SECRET env var)

    Returns:
        Base64-encoded HMAC token
    """
    if secret is None:
        secret = os.getenv("SERVICE_AUTH_SECRET")
        if not secret:
            raise ValueError(
                "SERVICE_AUTH_SECRET environment variable not set. "
                "Set it in .env.local or pass --secret flag"
            )

    if len(secret) < 32:
        raise ValueError("SERVICE_AUTH_SECRET must be at least 32 characters")

    # Create payload
    payload = {
        "orgId": org_id,
        "userId": user_id,
        "conversationId": conversation_id,
        "timestamp": int(time.time() * 1000),  # milliseconds
    }

    # Serialize payload
    payload_str = json.dumps(payload, separators=(",", ":"))

    # Generate HMAC signature
    signature = hmac.new(secret.encode(), payload_str.encode(), hashlib.sha256).hexdigest()

    # Combine payload and signature
    token_str = f"{payload_str}.{signature}"

    # Base64 encode
    token = base64.b64encode(token_str.encode()).decode()

    return token


def generate_mock_clerk_jwt(
    org_id: str = "default-org",
    user_id: str = "default-user",
    conversation_id: str = "00000000-0000-0000-0000-000000000001",
    secret: str = "your-secret-key-for-testing-at-least-32-chars-long",
    issuer: str = "https://clerk.test.com",
    audience: str = "hubble-agents",
    expiry_hours: int = 24,
) -> str:
    """Generate mock Clerk JWT token for testing

    WARNING: This generates a MOCK token for testing only.
    In production, tokens are generated by Clerk's servers.

    Args:
        org_id: Organization ID
        user_id: User ID
        conversation_id: Conversation ID
        secret: JWT signing secret (for testing only!)
        issuer: JWT issuer (Clerk domain)
        audience: JWT audience (your app)
        expiry_hours: Token expiry in hours

    Returns:
        JWT token string
    """
    if not HAS_JWT:
        raise ImportError(
            "PyJWT library not installed. "
            "Install with: uv add 'pyjwt[crypto]' or pip install 'pyjwt[crypto]'"
        )

    now = datetime.now(UTC)

    # Create JWT payload matching Clerk's structure
    payload = {
        # Standard JWT claims
        "iss": issuer,
        "sub": user_id,  # Subject = user ID
        "aud": audience,
        "exp": int((now + timedelta(hours=expiry_hours)).timestamp()),
        "iat": int(now.timestamp()),
        "nbf": int(now.timestamp()),
        # Custom claims for tenant isolation
        "org_id": org_id,
        "conversation_id": conversation_id,
        # Optional Clerk-like metadata
        "organizations": [
            {
                "id": org_id,
                "name": "Test Organization",
                "role": "admin",
            }
        ],
    }

    # Sign the JWT using HS256 (symmetric key for testing)
    # In production, Clerk uses RS256 (asymmetric keys)
    token = jwt.encode(payload, secret, algorithm="HS256")

    return token


def print_token_info(token: str, token_type: str) -> None:
    """Print token and usage instructions"""
    print(f"\n{'=' * 80}")
    print(f"Generated {token_type.upper()} Token")
    print(f"{'=' * 80}\n")

    print(f"Token:\n{token}\n")

    print("Usage with curl:")
    print(f"""
curl -X POST http://localhost:8000/api/chat \\
  -H "Authorization: Bearer {token}" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "messages": [{{"role": "user", "content": "Hello, test message"}}],
    "conversation_id": "00000000-0000-0000-0000-000000000001",
    "org_id": "default-org",
    "user_id": "default-user"
  }}'
""")

    print("Usage with Python requests:")
    print(f"""
import requests

response = requests.post(
    'http://localhost:8000/api/chat',
    headers={{
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json',
    }},
    json={{
        'messages': [{{'role': 'user', 'content': 'Hello, test message'}}],
        'conversation_id': '00000000-0000-0000-0000-000000000001',
        'org_id': 'default-org',
        'user_id': 'default-user',
    }},
)
print(response.json())
""")

    print(f"\n{'=' * 80}\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate authentication tokens for Hubble Agents API testing"
    )
    parser.add_argument(
        "--type",
        choices=["hmac", "jwt", "both"],
        default="both",
        help="Token type to generate (default: both)",
    )
    parser.add_argument(
        "--org-id",
        default="default-org",
        help="Organization ID (default: default-org)",
    )
    parser.add_argument(
        "--user-id",
        default="default-user",
        help="User ID (default: default-user)",
    )
    parser.add_argument(
        "--conversation-id",
        default="00000000-0000-0000-0000-000000000001",
        help="Conversation ID - must be valid UUID (default: 00000000-0000-0000-0000-000000000001)",
    )
    parser.add_argument(
        "--secret",
        help="HMAC secret (defaults to SERVICE_AUTH_SECRET env var)",
    )
    parser.add_argument(
        "--jwt-secret",
        default="your-secret-key-for-testing-at-least-32-chars-long",
        help="JWT signing secret for mock tokens (testing only!)",
    )
    parser.add_argument(
        "--issuer",
        default="https://clerk.test.com",
        help="JWT issuer (default: https://clerk.test.com)",
    )
    parser.add_argument(
        "--audience",
        default="hubble-agents",
        help="JWT audience (default: hubble-agents)",
    )
    parser.add_argument(
        "--expiry-hours",
        type=int,
        default=24,
        help="Token expiry in hours (default: 24)",
    )

    args = parser.parse_args()

    # Load .env.local if it exists
    env_file = Path(__file__).parent / ".env"
    if env_file.exists():
        print(f"Loading environment from {env_file}")
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    # Remove quotes if present
                    value = value.strip('"').strip("'")
                    os.environ.setdefault(key.strip(), value)

    try:
        # Generate HMAC token
        if args.type in ("hmac", "both"):
            hmac_token = generate_hmac_token(
                org_id=args.org_id,
                user_id=args.user_id,
                conversation_id=args.conversation_id,
                secret=args.secret,
            )
            print_token_info(hmac_token, "HMAC")

        # Generate JWT token
        if args.type in ("jwt", "both"):
            if not HAS_JWT:
                print("\nSkipping JWT token generation (PyJWT not installed)")
            else:
                jwt_token = generate_mock_clerk_jwt(
                    org_id=args.org_id,
                    user_id=args.user_id,
                    conversation_id=args.conversation_id,
                    secret=args.jwt_secret,
                    issuer=args.issuer,
                    audience=args.audience,
                    expiry_hours=args.expiry_hours,
                )
                print_token_info(jwt_token, "JWT (Mock Clerk)")

                print("NOTE: This is a MOCK JWT for testing only!")
                print("In production, use real Clerk tokens from your frontend.\n")

    except Exception as e:
        print(f"Error generating token: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
