packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@vercel/speed-insights"

onlyBuiltDependencies:
  - "@clerk/shared"
  - "@tailwindcss/oxide"
  - duckdb
  - esbuild
  - sharp
  - unrs-resolver
