"""Lazy SSE stream broker that opens streams when first CrewAI event arrives."""

from __future__ import annotations

import asyncio
import logging
from collections import defaultdict

from h10s.models.events import SSEvent

logger = logging.getLogger(__name__)


class LazySSEBroker:
    """SSE broker that activates streams when first CrewAI event arrives.

    Solves the run_id mismatch problem where:
    - API generates a correlation ID before crew execution
    - CrewAI generates its own internal run_id during kickoff
    - Stream needs to map between these identifiers
    """

    def __init__(self, retry_millis: int) -> None:
        self._pending: dict[str, asyncio.Queue[SSEvent | None]] = {}  # correlation_id -> queue
        self._active: dict[str, asyncio.Queue[SSEvent | None]] = {}  # crew_run_id -> queue
        self._correlation_map: dict[str, str] = {}  # correlation_id -> crew_run_id
        self._reverse_map: dict[str, str] = {}  # crew_run_id -> correlation_id
        self._sequence: defaultdict[str, int] = defaultdict(int)
        self._lock = asyncio.Lock()
        self._retry_millis = retry_millis
        self._cleanup_tasks: set[asyncio.Task[None]] = set()  # Track cleanup tasks

    @property
    def retry_millis(self) -> int:
        """Get retry interval in milliseconds."""
        return self._retry_millis

    async def create_pending_stream(self, correlation_id: str) -> asyncio.Queue[SSEvent | None]:
        """Create a pending stream that will activate when CrewAI events arrive.

        Args:
            correlation_id: Unique identifier generated by API layer

        Returns:
            Queue that will receive SSE events once activated
        """
        queue: asyncio.Queue[SSEvent | None] = asyncio.Queue()
        async with self._lock:
            self._pending[correlation_id] = queue
            logger.debug("Created pending stream for correlation_id=%s", correlation_id)

            # Schedule cleanup task to prevent memory leak if stream never activates
            task = asyncio.create_task(self._cleanup_pending_stream(correlation_id))
            self._cleanup_tasks.add(task)
            task.add_done_callback(self._cleanup_tasks.discard)
        return queue

    async def _cleanup_pending_stream(self, correlation_id: str, timeout: int = 300) -> None:
        """Clean up pending stream if not activated within timeout.

        Args:
            correlation_id: Correlation ID of pending stream
            timeout: Timeout in seconds before cleanup (default: 5 minutes)
        """
        await asyncio.sleep(timeout)
        async with self._lock:
            if correlation_id in self._pending:
                # Stream was never activated, clean it up
                queue = self._pending.pop(correlation_id)
                await queue.put(None)  # Signal end
                logger.warning(
                    "Cleaned up pending stream that was never activated: %s",
                    correlation_id,
                )

    async def activate_stream(self, crew_run_id: str, correlation_id: str) -> None:
        """Activate a pending stream when first CrewAI event arrives.

        Args:
            crew_run_id: The run_id generated by CrewAI internally
            correlation_id: The correlation_id from API layer (passed in crew inputs)
        """
        async with self._lock:
            if correlation_id in self._pending:
                # Move queue from pending to active
                queue = self._pending.pop(correlation_id)
                self._active[crew_run_id] = queue
                self._correlation_map[correlation_id] = crew_run_id
                self._reverse_map[crew_run_id] = correlation_id
                self._sequence[crew_run_id] = 0
                logger.info(
                    "Activated stream: correlation_id=%s -> crew_run_id=%s",
                    correlation_id,
                    crew_run_id,
                )
            else:
                # No pending stream found, create active stream directly
                # This handles cases where CrewAI events arrive before we set up the stream
                self._active[crew_run_id] = asyncio.Queue()
                self._sequence[crew_run_id] = 0
                logger.warning(
                    "No pending stream for correlation_id=%s, "
                    "created active stream for crew_run_id=%s",
                    correlation_id,
                    crew_run_id,
                )

    async def publish(self, event: SSEvent) -> None:
        """Publish event to the appropriate stream.

        Args:
            event: SSE event to publish
        """
        async with self._lock:
            queue = self._active.get(event.crew_run_id)

            if queue is None:
                # Try to find queue via correlation mapping
                correlation_id = self._reverse_map.get(event.crew_run_id)
                if correlation_id:
                    queue = self._active.get(event.crew_run_id)

                if queue is None:
                    logger.debug(
                        "No active stream for crew_run_id=%s, dropping event",
                        event.crew_run_id,
                    )
                    return

            # Add sequence number
            self._sequence[event.crew_run_id] += 1
            event.sequence = self._sequence[event.crew_run_id]

            # Set retry on first event
            if event.sequence == 1 and event.retry is None:
                event.retry = self._retry_millis

            # Put event in queue while holding lock to prevent race conditions
            await queue.put(event)
            logger.debug(
                "Queued SSE event crew_run_id=%s event=%s seq=%s",
                event.crew_run_id,
                event.event,
                event.sequence,
            )

    async def close(self, crew_run_id: str) -> None:
        """Close an active stream.

        Args:
            crew_run_id: The CrewAI run identifier
        """
        queue = self._active.pop(crew_run_id, None)
        self._sequence.pop(crew_run_id, None)

        # Clean up mapping
        correlation_id = self._reverse_map.pop(crew_run_id, None)
        if correlation_id:
            self._correlation_map.pop(correlation_id, None)

        if queue is not None:
            await queue.put(None)  # Signal stream end
            logger.debug("Closed stream for crew_run_id=%s", crew_run_id)

    def has_stream(self, crew_run_id: str) -> bool:
        """Check if an active stream exists for the given crew_run_id.

        Args:
            crew_run_id: The CrewAI run identifier

        Returns:
            True if active stream exists
        """
        return crew_run_id in self._active


__all__ = ["LazySSEBroker"]
