"""Response models returned by the agents API."""

from __future__ import annotations

from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """Structured response for API consumers."""

    summary: str = Field(description="High-level answer provided to the caller.")
    actions: list[str] = Field(
        default_factory=list,
        description="Actionable next steps recommended by the crew.",
    )
    raw: str | None = Field(
        default=None,
        description="Raw text generated by the crew. Useful for debugging or UI fallbacks.",
    )
    tokens: int | None = Field(
        default=None,
        description="Approximate token usage for the run, when available.",
    )
