"""FastAPI application exposing the authenticated CrewAI workflow with persistence."""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from typing import Any

from fastapi import Depends, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from sse_starlette.sse import EventSourceResponse

from .config.settings import validate_environment
from .crew import AuthenticatedSupportCrew
from .middleware.auth import ServiceTokenPayload, get_current_user
from .middleware.rate_limit import check_rate_limit
from .middleware.security import SecurityHeadersMiddleware
from .models import ChatRequest, ChatResponse
from .persistence.database import SupabaseDatabase
from .persistence.repository import ChatRepository
from .runtime import CrewRunService
from .telemetry import configure_telemetry

logger = logging.getLogger(__name__)
settings = validate_environment()
crew_factory = AuthenticatedSupportCrew()
database = SupabaseDatabase()
chat_repository = ChatRepository(database)
run_service = CrewRunService(crew_factory, chat_repository)

app = FastAPI(
    title="Hubble Agents API",
    version="1.0.0",
    docs_url=None if settings.environment == "production" else "/docs",
    redoc_url=None,
)

app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=["*.fly.dev", "localhost", "127.0.0.1", "testserver"],
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.dashboard_url],
    allow_credentials=True,
    allow_methods=["POST", "GET"],
    allow_headers=["Authorization", "X-User-Id", "X-Org-Id", "X-Conversation-Id"],
    max_age=600,
)


@app.on_event("startup")
async def startup() -> None:
    """Initialise shared services."""

    await database.connect(settings)
    configure_telemetry(app, settings)


@app.on_event("shutdown")
async def shutdown() -> None:
    """Dispose shared services."""

    await database.close()


@app.get("/health")
async def health() -> dict[str, Any]:
    """Return a basic health payload."""

    return {
        "status": "healthy",
        "service": "agent-backend",
        "environment": settings.environment,
    }


@app.post("/api/chat", response_model=ChatResponse)
async def chat_response(
    request: ChatRequest,
    current_user: ServiceTokenPayload = Depends(get_current_user),  # noqa: B008
    _rate_limit: None = Depends(check_rate_limit),
) -> ChatResponse:
    """Return a structured response generated by the CrewAI orchestrator."""

    _validate_user(request, current_user)

    if not request.messages:
        raise HTTPException(status_code=400, detail="At least one message is required")

    try:
        outcome = await run_service.run(request, current_user)
    except Exception as exc:  # pragma: no cover - defensive logging
        logger.exception(
            "Crew execution failed", extra={"conversation_id": request.conversation_id}
        )
        raise HTTPException(status_code=500, detail=f"Crew execution failed: {exc}") from exc

    return ChatResponse(
        summary=outcome.summary, actions=outcome.actions, raw=outcome.raw, tokens=outcome.tokens
    )


@app.post("/api/chat/stream")
async def chat_stream(
    request: ChatRequest,
    current_user: ServiceTokenPayload = Depends(get_current_user),  # noqa: B008
    _rate_limit: None = Depends(check_rate_limit),
) -> EventSourceResponse:
    """Stream crew execution events back to the caller via Server-Sent Events."""

    _validate_user(request, current_user)

    if not request.messages:
        raise HTTPException(status_code=400, detail="At least one message is required")

    try:
        _session, iterator = await run_service.stream(request, current_user)
    except Exception as exc:  # pragma: no cover - defensive logging
        logger.exception(
            "Failed to start streaming run", extra={"conversation_id": request.conversation_id}
        )
        raise HTTPException(
            status_code=500, detail=f"Unable to start streaming run: {exc}"
        ) from exc

    async def event_generator() -> AsyncIterator[dict[str, str]]:
        async for event in iterator:
            yield event.as_sse()

    return EventSourceResponse(event_generator(), ping=15000)


def _validate_user(request: ChatRequest, current_user: ServiceTokenPayload) -> None:
    if (
        request.org_id != current_user.org_id
        or request.user_id != current_user.user_id
        or request.conversation_id != current_user.conversation_id
    ):
        raise HTTPException(status_code=403, detail="Request does not match authenticated user")
